CREATE TABLE final_airbnb(
   ntaname_1 VARCHAR(56) NOT NULL PRIMARY KEY
  ,number    INTEGER  NOT NULL
);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Airport',1);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Allerton-Pelham Gardens',41);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Annadale-Huguenot-Prince''s Bay-Eltingville',6);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Arden Heights',1);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Astoria',795);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Auburndale',19);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Baisley Park',84);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bath Beach',14);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Battery Park City-Lower Manhattan',753);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bay Ridge',195);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bayside-Bayside Hills',28);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bedford',1407);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bedford Park-Fordham North',27);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bellerose',8);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Belmont',21);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bensonhurst East',30);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bensonhurst West',73);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Borough Park',70);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Breezy Point-Belle Harbor-Rockaway Park-Broad Channel',20);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Briarwood-Jamaica Hills',69);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Brighton Beach',73);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bronxdale',20);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Brooklyn Heights-Cobble Hill',168);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Brownsville',36);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bushwick North',1179);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Bushwick South',1766);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Cambria Heights',19);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Canarsie',144);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Carroll Gardens-Columbia Street-Red Hook',454);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Central Harlem North-Polo Grounds',880);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Central Harlem South',795);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Charleston-Richmond Valley-Tottenville',6);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Chinatown',928);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Claremont-Bathgate',10);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Clinton',1778);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Clinton Hill',908);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Co-op City',15);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('College Point',21);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Corona',49);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Crotona Park East',10);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Crown Heights North',1455);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Crown Heights South',262);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Cypress Hills-City Line',116);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('DUMBO-Vinegar Hill-Downtown Brooklyn-Boerum Hill',463);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Douglas Manor-Douglaston-Little Neck',13);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Dyker Heights',21);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East Concourse-Concourse Village',46);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East Elmhurst',61);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East Flatbush-Farragut',146);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East Flushing',81);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East Harlem North',558);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East Harlem South',506);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East New York',175);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East New York (Pennsylvania Ave)',44);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East Tremont',12);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East Village',1425);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('East Williamsburg',1240);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Eastchester-Edenwald-Baychester',21);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Elmhurst',189);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Elmhurst-Maspeth',94);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Erasmus',184);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Far Rockaway-Bayswater',47);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Flatbush',542);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Flatlands',83);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Flushing',168);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Fordham South',12);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Forest Hills',169);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Fort Greene',466);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Fresh Meadows-Utopia',17);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Ft. Totten-Bay Terrace-Clearview',6);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Georgetown-Marine Park-Bergen Beach-Mill Basin',19);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Glendale',41);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Gramercy',486);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Grasmere-Arrochar-Ft. Wadsworth',29);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Gravesend',32);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Great Kills',14);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Greenpoint',1050);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Grymes Hill-Clifton-Fox Hills',21);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Hamilton Heights',771);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Hammels-Arverne-Edgemere',132);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Highbridge',31);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Hollis',19);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Homecrest',53);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Hudson Yards-Chelsea-Flatiron-Union Square',1480);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Hunters Point-Sunnyside-West Maspeth',565);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Hunts Point',19);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Jackson Heights',247);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Jamaica',26);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Jamaica Estates-Holliswood',15);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Kensington-Ocean Parkway',136);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Kew Gardens',48);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Kew Gardens Hills',25);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Kingsbridge Heights',10);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Laurelton',26);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Lenox Hill-Roosevelt Island',815);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Lincoln Square',501);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Lindenwood-Howard Beach',20);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Longwood',13);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Lower East Side',897);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Madison',42);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Manhattanville',351);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Marble Hill-Inwood',166);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Mariner''s Harbor-Arlington-Port Ivory-Graniteville',15);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Maspeth',54);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Melrose South-Mott Haven North',20);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Middle Village',40);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Midtown-Midtown South',1053);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Midwood',88);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Morningside Heights',720);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Morrisania-Melrose',40);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Mott Haven-Port Morris',102);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Mount Hope',32);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Murray Hill',49);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Murray Hill-Kips Bay',904);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('New Brighton-Silver Lake',34);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('New Dorp-Midland Beach',16);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('New Springville-Bloomfield-Travis',12);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('North Corona',43);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('North Riverdale-Fieldston-Riverdale',22);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('North Side-South Side',2366);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Norwood',22);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Oakland Gardens',11);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Oakwood-Oakwood Beach',4);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Ocean Hill',317);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Ocean Parkway South',18);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Old Astoria',243);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Old Town-Dongan Hills-South Beach',24);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Ozone Park',25);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Park Slope-Gowanus',997);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Parkchester',19);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Pelham Bay-Country Club-City Island',29);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Pelham Parkway',32);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Pomonok-Flushing Heights-Hillcrest',29);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Port Richmond',9);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Prospect Heights',454);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Prospect Lefferts Gardens-Wingate',656);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Queens Village',56);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Queensboro Hill',67);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Queensbridge-Ravenswood-Long Island City',181);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Rego Park',75);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Richmond Hill',76);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Ridgewood',436);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Rosedale',48);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Rossville-Woodrow',3);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Rugby-Remsen Village',94);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Schuylerville-Throgs Neck-Edgewater Park',30);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Seagate-Coney Island',27);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Sheepshead Bay-Gerritsen Beach-Manhattan Beach',76);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('SoHo-TriBeCa-Civic Center-Little Italy',1140);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Soundview-Bruckner',8);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Soundview-Castle Hill-Clason Point-Harding Park',29);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('South Jamaica',40);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('South Ozone Park',40);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Springfield Gardens North',56);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Springfield Gardens South-Brookville',59);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Spuyten Duyvil-Kingsbridge',35);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('St. Albans',92);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Stapleton-Rosebank',60);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Starrett City',2);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Steinway',339);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Stuyvesant Heights',1462);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Stuyvesant Town-Cooper Village',34);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Sunset Park East',152);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Sunset Park West',254);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Todt Hill-Emerson Hill-Heartland Village-Lighthouse Hill',11);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Turtle Bay-East Midtown',961);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('University Heights-Morris Heights',39);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Upper East Side-Carnegie Hill',335);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Upper West Side',1229);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Van Cortlandt Village',37);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Van Nest-Morris Park-Westchester Square',17);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Washington Heights North',349);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Washington Heights South',595);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('West Brighton',1);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('West Concourse',62);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('West Farms-Bronx River',16);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('West New Brighton-New Brighton-St. George',78);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('West Village',1316);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Westchester-Unionport',10);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Westerleigh',8);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Whitestone',15);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Williamsbridge-Olinville',49);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Williamsburg',74);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Windsor Terrace',202);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Woodhaven',95);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Woodlawn-Wakefield',36);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Woodside',211);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('Yorkville',790);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('park-cemetery-etc-Bronx',5);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('park-cemetery-etc-Brooklyn',22);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('park-cemetery-etc-Manhattan',43);
INSERT INTO final_airbnb(ntaname_1,number) VALUES ('park-cemetery-etc-Queens',24);
